# Generated by Django 5.1.7 on 2025-04-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('username', models.CharField(max_length=90, verbose_name='Имя')),
                ('email', models.EmailField(max_length=55, unique=True, verbose_name='Электронная почта')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Телефон')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ('username',),
            },
        ),
    ]
